### ISSUE TITLE
Use new impressionist version (from Github), fixing deprecation warnings

### ISSUE THREAD

**Issue by Riscky** [svsticky/constipated-koala#526]
DEPRECATION WARNING: ActionDispatch::Http::ParameterFilter is deprecated and will be removed from Rails 6.1. Use ActiveSupport::ParameterFilter instead. (called from destroy at /app/controllers/admin/members_controller.rb:148)

**Comment by Riscky** [comment]
This seems to be in the impressionist package.
This fork has a fix: https://github.com/alexander-alyoshin/impressionist/
The impressionist packaged doesn't receive a lot of love anymore, maybe we'll have to switch at some point.

**Comment by Riscky** [comment]
Installing the fork generates the following error:
```
Error:
MembersControllerTest#test_should_destroy_member:
NoMethodError: undefined method `cookie_value' for "37016bebfbe1333539a8728a1db39df7":String
    app/controllers/admin/members_controller.rb:152:in `destroy'
    test/controllers/admin/members_controller_test.rb:29:in `block (2 levels) in <class:MembersControllerTest>'
    test/controllers/admin/members_controller_test.rb:28:in `block in <class:MembersControllerTest>
```

**Comment by Riscky** [comment]
Impressionist is alive once again!
We should use the new 2.0.0 release

**Comment by Riscky** [comment]
https://github.com/charlotte-ruby/impressionist/releases/tag/v2.0.0
