### ISSUE TITLE
Ugly error on user credentials/preferences changing when missing mailchimp ENV

### ISSUE THREAD

**Issue by Raymonzut** [svsticky/constipated-koala#870]
### Expected behaviour
When saving your user credentials, either changed or unchanged, this should be handled something like "we can not change your user credentials at this time" when missing back-end options
Bonus: only on fields that require these dependencies should this be raised.

### Actual behavior
Status 500 is thrown regardless of what you change:

```
Started POST "/edit" for ::1 at 2021-08-27 10:54:12 +0200
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 3], ["LIMIT", 1]]
  
ActionController::BadRequest (Invalid request parameters: expected Array (got Rack::QueryParser::Params) for param `mailchimp_interests'):
  
/nix/store/m84jw82s2p9af3m1m3kfxfz1saawqjnv-ruby2.7.3-rack-2.2.3/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/query_parser.rb:109:in `normalize_params'

...

ArgumentError: wrong number of arguments (given 2, expected 3)
        from /nix/store/s4jrfs3mpln1gj8c6xhv554j3mfq6im2-ruby2.7.3-actionview-6.1.4/lib/ruby/gems/2.7.0/gems/actionview-6.1.4/lib/action_view/base.rb:230:in `initialize'
        from /nix/store/j6kpirfsqcs76f0k38nqzay6aqq359ln-ruby2.7.3-web-console-4.0.1/lib/ruby/gems/2.7.0/gems/web-console-4.0.1/lib/web_console/template.rb:20:in `new'

...
```
### Steps to reproduce
- checkout development@ 4e60648a20b3338be25eba20a4022e2dca2f8ccb
- leave out mailchimp ENV
- user -> edit credentials/profile info -> save changes
- browser: any

**Comment by Raymonzut** [comment]
Fixed by #871
