### ISSUE TITLE
Sentry: Checkout balance or price equal to Nil

### ISSUE THREAD

**Issue by Riscky** [svsticky/constipated-koala#937]
Full error:

`NoMethodError: undefined method `+' for nil:NilClass
  app/models/checkout_transaction.rb:28:in `validate_sufficient_credit'
    errors.add(:price, I18n.t('price.insufficient_credit', scope: i18n_error_scope)) if price + checkout_balance.balance < 0
  app/controllers/api/checkout_controller.rb:39:in `purchase'
    if transaction.save!`

**Comment by Riscky** [comment]
Duplicate of #912
